//! Checks the translator against fixtures produced by real `java.util.regex`.
//!
//! The fixtures are generated by `tools/java-regex-oracle` (see its README) and committed;
//! this test never needs Java. Every record is replayed and compared to what Java answered.

#![expect(clippy::expect_used, reason = "test code")]

use std::collections::BTreeMap;

use apigw_regex::{JavaRegex, RegexError, Replacement};
use serde::Deserialize;
use serde_json::Value;

const FIXTURES: &str = include_str!("fixtures/java-regex.jsonl");

/// Patterns Java accepts but this crate refuses with a typed "unsupported" error.
const UNTRANSLATABLE: &[&str] = &[
    r"\Ga",
    r"\G",
    r"\X",
    r"\N{LATIN SMALL LETTER A}",
    r"\b{g}",
    r"\p{javaLowerCase}",
    r"\p{InGreek}",
    r"\p{block=Greek}",
    r"\ud83d",
    r"\ude00",
    r"(?U)\p{Graph}",
    r"(?i)(a)\1",
];

/// A case whose result differs from Java in a way a translation cannot fix.
struct Divergence {
    pattern: &'static str,
    /// The input that differs, or `None` when every input of the pattern may differ.
    input: Option<&'static str>,
    reason: &'static str,
}

impl Divergence {
    fn matches(&self, record: &Record) -> bool {
        self.pattern == record.pattern
            && self
                .input
                .is_none_or(|input| record.input.as_deref() == Some(input))
    }
}

const EMPTY_ITERATION: &str = "Java records an empty final iteration of a repeated group; the engine keeps the last non-empty one";
const COMBINING_MARKS: &str = "Java treats a combining mark after a letter as a word character for \\b; the translation uses ASCII word characters only";
const DOTTED_I: &str = "Java compares case-insensitive Unicode text through toUpperCase/toLowerCase, which equates dotted and dotless i with i and I; the engine uses simple case folding";

const KNOWN_DIVERGENCES: &[Divergence] = &[
    Divergence {
        pattern: r"(^)*a",
        input: None,
        reason: EMPTY_ITERATION,
    },
    Divergence {
        pattern: r"(a*)*",
        input: None,
        reason: EMPTY_ITERATION,
    },
    Divergence {
        pattern: r"(a*)+",
        input: None,
        reason: EMPTY_ITERATION,
    },
    Divergence {
        pattern: r"(a?)*",
        input: None,
        reason: EMPTY_ITERATION,
    },
    Divergence {
        pattern: r"\b",
        input: Some("e\u{301} x"),
        reason: COMBINING_MARKS,
    },
    Divergence {
        pattern: r"\b",
        input: Some("a\u{301}b"),
        reason: COMBINING_MARKS,
    },
    Divergence {
        pattern: r"\bx",
        input: Some("e\u{301}x"),
        reason: COMBINING_MARKS,
    },
    Divergence {
        pattern: r"(?iu)i",
        input: Some("\u{130}"),
        reason: DOTTED_I,
    },
    Divergence {
        pattern: r"(?iu)i",
        input: Some("\u{131}"),
        reason: DOTTED_I,
    },
    Divergence {
        pattern: "(?iu)\u{131}",
        input: None,
        reason: DOTTED_I,
    },
];

#[derive(Debug, Deserialize)]
struct Record {
    pattern: String,
    op: String,
    input: Option<String>,
    arg: Option<Value>,
    expected: Value,
}

fn utf16_offset(input: &str, byte: usize) -> usize {
    input
        .get(..byte)
        .map_or(0, |prefix| prefix.encode_utf16().count())
}

fn expect_error(value: &Value) -> bool {
    value.get("error").is_some()
}

fn check(record: &Record, regex: &JavaRegex) -> Result<(), String> {
    let input = record.input.as_deref().unwrap_or_default();
    match record.op.as_str() {
        "matches" => {
            let got = regex.matches(input).map_err(|e| e.to_string())?;
            (Value::Bool(got) == record.expected)
                .then_some(())
                .ok_or_else(|| format!("matches: got {got}, java {}", record.expected))
        }
        "find" => check_find(record, regex, input),
        "find_all" => {
            let mut spans = Vec::new();
            for found in regex.find_iter(input) {
                let found = found.map_err(|e| e.to_string())?;
                spans.push(Value::from(vec![
                    utf16_offset(input, found.start()),
                    utf16_offset(input, found.end()),
                ]));
            }
            let got = Value::Array(spans);
            (got == record.expected)
                .then_some(())
                .ok_or_else(|| format!("find_all: got {got}, java {}", record.expected))
        }
        "replace_all" | "replace_first" => check_replace(record, regex, input),
        "split" => {
            let limit = record
                .arg
                .as_ref()
                .and_then(Value::as_i64)
                .and_then(|limit| i32::try_from(limit).ok())
                .ok_or("split without a limit")?;
            let parts = regex.split(input, limit).map_err(|e| e.to_string())?;
            let got = Value::from(parts);
            (got == record.expected)
                .then_some(())
                .ok_or_else(|| format!("split({limit}): got {got}, java {}", record.expected))
        }
        other => Err(format!("unknown op {other}")),
    }
}

fn check_find(record: &Record, regex: &JavaRegex, input: &str) -> Result<(), String> {
    let captures = regex.captures(input).map_err(|e| e.to_string())?;
    let Some(captures) = captures else {
        return record
            .expected
            .is_null()
            .then_some(())
            .ok_or_else(|| format!("find: got none, java {}", record.expected));
    };
    let whole = captures.whole().ok_or("find without group 0")?;
    let groups: Vec<Value> = captures
        .iter()
        .map(|group| group.map_or(Value::Null, |g| Value::from(g.as_str())))
        .collect();
    let got = serde_json::json!({
        "start": utf16_offset(input, whole.start()),
        "end": utf16_offset(input, whole.end()),
        "groups": groups,
    });
    (got == record.expected)
        .then_some(())
        .ok_or_else(|| format!("find: got {got}, java {}", record.expected))
}

fn check_replace(record: &Record, regex: &JavaRegex, input: &str) -> Result<(), String> {
    let replacement = record
        .arg
        .as_ref()
        .and_then(Value::as_str)
        .ok_or("replace without a replacement")?;
    let replacement = Replacement::from(replacement);
    let result = if record.op == "replace_all" {
        regex.replace_all(input, &replacement)
    } else {
        regex.replace_first(input, &replacement)
    };
    match result {
        Ok(got) => {
            let got = Value::from(got);
            (got == record.expected)
                .then_some(())
                .ok_or_else(|| format!("{}: got {got}, java {}", record.op, record.expected))
        }
        Err(RegexError::Replacement(err)) => expect_error(&record.expected)
            .then_some(())
            .ok_or_else(|| format!("{}: got error {err}, java {}", record.op, record.expected)),
        Err(other) => Err(format!("{}: unexpected error {other}", record.op)),
    }
}

#[test]
fn matches_java_util_regex() {
    let mut by_pattern: BTreeMap<String, Vec<Record>> = BTreeMap::new();
    for line in FIXTURES.lines() {
        let record: Record = serde_json::from_str(line).expect("fixture line is valid JSON");
        by_pattern
            .entry(record.pattern.clone())
            .or_default()
            .push(record);
    }

    let mut failures = Vec::new();
    let mut checked = 0_usize;
    let mut explained = vec![false; KNOWN_DIVERGENCES.len()];
    for (pattern, records) in &by_pattern {
        let compiled = JavaRegex::new(pattern);
        let java_rejects = records
            .iter()
            .any(|r| r.op == "compile" && expect_error(&r.expected));
        match compiled {
            Err(_) if java_rejects => checked += 1,
            Err(err) if err.is_untranslatable() => {
                if UNTRANSLATABLE.contains(&pattern.as_str()) {
                    checked += 1;
                } else {
                    failures.push(format!("{pattern:?}: unexpectedly untranslatable: {err}"));
                }
            }
            Err(err) => failures.push(format!("{pattern:?}: rejected a valid pattern: {err}")),
            Ok(_) if java_rejects => {
                failures.push(format!("{pattern:?}: accepted but java rejects it"));
            }
            Ok(regex) => {
                if UNTRANSLATABLE.contains(&pattern.as_str()) {
                    failures.push(format!(
                        "{pattern:?}: listed as untranslatable but compiles"
                    ));
                }
                let mut mismatches: Vec<(&Record, String)> = Vec::new();
                for record in records.iter().filter(|r| r.op != "compile") {
                    checked += 1;
                    if let Err(why) = check(record, &regex) {
                        mismatches.push((
                            record,
                            format!(
                                "{pattern:?} {} {:?} {:?}: {why}",
                                record.op, record.input, record.arg
                            ),
                        ));
                    }
                }
                for (record, message) in mismatches {
                    match KNOWN_DIVERGENCES.iter().position(|d| d.matches(record)) {
                        Some(index) => {
                            if let Some(used) = explained.get_mut(index) {
                                *used = true;
                            }
                        }
                        None => failures.push(message),
                    }
                }
            }
        }
    }
    for (divergence, used) in KNOWN_DIVERGENCES.iter().zip(explained) {
        if !used {
            failures.push(format!(
                "{:?} {:?}: listed as divergent but matches java ({})",
                divergence.pattern, divergence.input, divergence.reason
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "{} of {checked} fixture checks failed:\n{}",
        failures.len(),
        failures.join("\n")
    );
}
