//! Replays the oracle corpus: every template in `tools/vtl-oracle/cases/*.json` is rendered and
//! compared with what Apache Velocity 1.7 produced for it (`*.expected.jsonl`, regenerated by
//! `tools/vtl-oracle/run.sh`).

#![expect(clippy::expect_used, reason = "test code")]
#![expect(clippy::unwrap_used, reason = "test code")]

use std::collections::BTreeMap;
use std::fs;
use std::path::PathBuf;

use apigw_vtl::{InputParams, Map, Renderer, SimpleInput, Template, Value};
use serde::Deserialize;

/// Cases whose output differs from Velocity for a reason that cannot be fixed, with the reason.
/// Each entry must still differ, or the test fails so that the list stays honest.
const KNOWN_DIVERGENCES: &[(&str, &str)] = &[
    (
        "random.1.463",
        "Velocity lexes the text after `$ref.prop(#end` in its method-argument state and fails; we read it as plain text",
    ),
    (
        "random.1.493",
        "`#set($s = (null * x) + y)` appends the null math node's source text in Velocity; we append only a null reference's text",
    ),
    (
        "random.1.511",
        "Velocity fails on `(\\ = 'b')` after a property reference and a `#set`; its lexer state is not reproduced",
    ),
    (
        "random.1.544",
        "Velocity fails on a `$b#if(..)` sequence after a property reference followed by `.name(`; its lexer state is not reproduced",
    ),
];

/// One template with the request fields it overrides; the rest come from `defaults.json`.
#[derive(Debug, Deserialize)]
struct Case {
    name: String,
    template: String,
    #[serde(default)]
    context: Option<serde_json::Value>,
    #[serde(default)]
    body: Option<String>,
    #[serde(default, rename = "bodyJson")]
    body_json: Option<serde_json::Value>,
    #[serde(default)]
    params: Option<serde_json::Value>,
    #[serde(default, rename = "stageVariables")]
    stage_variables: Option<serde_json::Value>,
}

/// The request every case starts from unless it sets its own fields.
#[derive(Debug, Deserialize)]
struct Defaults {
    context: serde_json::Value,
    #[serde(rename = "bodyJson")]
    body_json: serde_json::Value,
    params: serde_json::Value,
    #[serde(rename = "stageVariables")]
    stage_variables: serde_json::Value,
}

#[derive(Debug, Deserialize)]
struct Expected {
    name: String,
    output: Option<String>,
    context: Option<serde_json::Value>,
    error: Option<String>,
}

fn cases_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../tools/vtl-oracle/cases")
}

fn map_from(json: Option<&serde_json::Value>) -> Map {
    match json.map(Value::from) {
        Some(Value::Map(map)) => map,
        _ => Map::new(),
    }
}

fn params_from(json: Option<&serde_json::Value>) -> InputParams {
    let groups = map_from(json);
    let group = |name: &str| match groups.get(name) {
        Some(Value::Map(map)) => map,
        _ => Map::new(),
    };
    InputParams {
        path: group("path"),
        querystring: group("querystring"),
        header: group("header"),
    }
}

fn render(case: &Case, defaults: &Defaults) -> Result<(String, String), String> {
    let template = Template::parse(&case.template).map_err(|err| format!("parse: {err}"))?;
    let body = match (&case.body, &case.body_json) {
        (Some(body), _) => body.clone(),
        (None, json) => serde_json::to_string(json.as_ref().unwrap_or(&defaults.body_json))
            .map_err(|err| err.to_string())?,
    };
    let input = SimpleInput::new(
        body,
        params_from(Some(case.params.as_ref().unwrap_or(&defaults.params))),
    );
    let context = map_from(Some(case.context.as_ref().unwrap_or(&defaults.context)));
    let stage_variables = map_from(Some(
        case.stage_variables
            .as_ref()
            .unwrap_or(&defaults.stage_variables),
    ));
    let output = Renderer::new(&input)
        .with_context(context.clone())
        .with_stage_variables(stage_variables)
        .render(&template)
        .map_err(|err| format!("render: {err}"))?;
    let context_json = Value::Map(context)
        .to_json()
        .map_err(|err| err.to_string())?;
    Ok((output, context_json))
}

fn compare(case: &Case, defaults: &Defaults, expected: &Expected) -> Result<(), String> {
    let got = render(case, defaults);
    match (&expected.error, got) {
        (Some(_), Err(_)) => Ok(()),
        (Some(error), Ok((output, _))) => Err(format!(
            "velocity failed with {error}, got output {output:?}"
        )),
        (None, Err(err)) => Err(format!(
            "velocity rendered {:?}, got error {err}",
            expected.output
        )),
        (None, Ok((output, context))) => {
            let want = expected.output.as_deref().unwrap_or_default();
            if output != want {
                return Err(format!(
                    "output differs\n  velocity: {want:?}\n  ours:     {output:?}"
                ));
            }
            let want_context = expected
                .context
                .as_ref()
                .map(|json| Value::from(json).to_json().unwrap_or_default())
                .unwrap_or_default();
            if context != want_context {
                return Err(format!(
                    "context differs\n  velocity: {want_context}\n  ours:     {context}"
                ));
            }
            Ok(())
        }
    }
}

#[test]
fn matches_apache_velocity() {
    let mut files: Vec<PathBuf> = fs::read_dir(cases_dir())
        .expect("cases directory exists")
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| {
            path.extension().is_some_and(|ext| ext == "json")
                && path.file_stem().is_some_and(|stem| stem != "defaults")
        })
        .collect();
    files.sort();
    let defaults: Defaults =
        serde_json::from_str(&fs::read_to_string(cases_dir().join("defaults.json")).unwrap())
            .expect("defaults parse");
    assert!(!files.is_empty(), "no oracle cases found");

    let mut failures = Vec::new();
    let mut explained = vec![false; KNOWN_DIVERGENCES.len()];
    let mut checked = 0_usize;
    for file in files {
        let cases: Vec<Case> =
            serde_json::from_str(&fs::read_to_string(&file).unwrap()).expect("cases parse");
        let expected_path = file.with_extension("expected.jsonl");
        let expected_text = fs::read_to_string(&expected_path).unwrap_or_default();
        assert!(
            !expected_text.is_empty(),
            "missing or empty {}",
            expected_path.display()
        );
        let expected: BTreeMap<String, Expected> = expected_text
            .lines()
            .map(|line| serde_json::from_str::<Expected>(line).expect("expected line parses"))
            .map(|entry| (entry.name.clone(), entry))
            .collect();
        for case in &cases {
            let Some(want) = expected.get(&case.name) else {
                failures.push(format!("{}: no expected output recorded", case.name));
                continue;
            };
            checked += 1;
            let known = KNOWN_DIVERGENCES
                .iter()
                .position(|(name, _)| *name == case.name);
            match (compare(case, &defaults, want), known) {
                (Ok(()), None) => {}
                (Ok(()), Some(_)) => failures.push(format!(
                    "{}: listed as divergent but matches velocity",
                    case.name
                )),
                (Err(why), None) => failures.push(format!(
                    "{}: {why}\n  template: {:?}",
                    case.name, case.template
                )),
                (Err(_), Some(index)) => {
                    if let Some(used) = explained.get_mut(index) {
                        *used = true;
                    }
                }
            }
        }
    }
    for ((name, _), used) in KNOWN_DIVERGENCES.iter().zip(&explained) {
        if !used {
            failures.push(format!("{name}: listed as divergent but never ran"));
        }
    }
    assert!(
        failures.is_empty(),
        "{} of {checked} oracle cases differ from Apache Velocity 1.7:\n{}",
        failures.len(),
        failures.join("\n")
    );
}
